### PR TITLE
Bug/37 fix error message component

### LINKED ISSUE #37: Fix error message component
Stop same error message from being displayed twice

### LINKED ISSUE #38: Fix favicon, title
Favicon is not showing on tabs, title is wrongly displayed.

### PR DESCRIPTION
**Pull request by jgf20**
- Resolved #38 
    - Add favicon files
    - Fix title logic in app.component.ts
- Resolved #37 
    - Add validation to messages to avoid duplicated messages to appear

### CODE REVIEW

File: src/app/app.component.ts [hunk 1]
```diff
@@ -31,35 +29,37 @@ export class AppComponent {
...
-			title = ((activatedRoutes.length > 2 && idx === 1) ? " | ":"")+title;
-
+			let titleAux = this.getTitle(snapshot);
+			if( activatedRoutes.length > 2 && idx !== activatedRoutes.length - 1 ) {
+				title += " > " + titleAux;
+				return;
+			}
+			if( titleAux === "Workbench") return;
+			title += titleAux;
+			console.log( title );
```
Comment (alvaro9210) [inline src/app/app.component.ts]: Remove console log. Make sure to reformat code.

File: src/app/shared/messages-area/messages-area.component.ts [hunk 2]
```diff
@@ -21,7 +22,14 @@ export class MessagesAreaComponent implements AfterViewInit {
 	ngAfterViewInit():void {
 		this.messagesAreaService.addMessageEmitter.subscribe(
 			( message ):void => {
-				this.messages.push( message );
+				this.messages.forEach( ( messageAux )=> {
+					if( messageAux.statusCode !== message.statusCode ) return;
```
Comment (alvaro9210) [inline src/app/shared/messages-area/messages-area.component.ts]: What happens if there are two messages with same statusCode but different messages?
Should we decide to compare also other Message properties like title, content, etc? (Just a question)
Also, a global boolean (`messageExists`) to ask if it already exists doesn't seem necessary, it's just being used within this scope.
Also, check the [`array.some`](https://developer.mozilla.org/es/docs/Web/JavaScript/Referencia/Objetos_globales/Array/some) operator to ask for a boolean matching a condition within an array.

**Comment by alvaro9210** [comment]
Assigning Miguel as the reviewer to make a final review so he can proceed to merge or request changes if he finds any improvements that can be applied.
