### PR TITLE
Bug/#71 - SPARQL client set disabled execute button

### LINKED ISSUE #71: The SPARQL client set disabled execute button on empty endpoint
The SPARQL client seems to accept relative URIs, but if one does not provide anything in the `Endpoint URI` input the `Execute` button remains disabled.

One can actually write something in the input to enable the button and then erase it and it will remain enabled.

An indication of relatives URIs must be set, and/or some default value like `/` or the `host` of the connected platform.

### LINKED ISSUE #72: SPARQL Construct and Select combination
When creating queries using `Construct` + `Select` the Workbench breaks and misbehaves.

### LINKED ISSUE #74: Inverted success message on document-ap creation
After creating a Document the message displays a successful Access Point creation and when creating an Access Point, the message shows a successful Document creation. 
Messages are inverted.

### PR DESCRIPTION
**Pull request by alvaro9210**
- Resolved #74 - Inverted success message on Documents and Access Points creation
- Resolved #72 - CONSTRUCT and SELECT combination serve wrong output formats of CONSTRUCTS
- Resolved #71 - The SPARQL client set disabled execute button on empty endpoint

### CODE REVIEW

File: src/app/root-content/sparql-client/sparql-client.component.ts [hunk 1]
```diff
@@ -297,12 +298,12 @@ export class SPARQLClientComponent implements OnInit, AfterViewInit {
...
-			case (this.regExpSelect.test( query )):
-				return this.sparqlQueryOperations.select.name;
 			case (this.regExpConstruct.test( query )):
 				return this.sparqlQueryOperations.construct.name;
 			case (this.regExpAsk.test( query )):
 				return this.sparqlQueryOperations.ask.name;
+			case (this.regExpSelect.test( query )):
+				return this.sparqlQueryOperations.select.name;
 			case (this.regExpDescribe.test( query )):
 				return this.sparqlQueryOperations.describe.name;
```
Comment (MiguelAraCo) [inline src/app/root-content/sparql-client/sparql-client.component.ts]: DESCRIBE queries can also have sub SELECT queries
